# Generated by Django 3.0.7 on 2020-06-11 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_remove_user_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_bio',
            field=models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='film_preferences',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='literature_preferences',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='music_preferences',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='other_interests',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='political_preferences',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='television_preferences',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
