# Generated by Django 3.0.7 on 2020-06-10 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liked', '0002_auto_20200610_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='liked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
