# Generated by Django 3.0.7 on 2020-06-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='reponse',
            new_name='response',
        ),
    ]
