# Generated by Django 3.0.7 on 2020-06-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_auto_20200610_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='response',
            new_name='reply',
        ),
    ]
