# Generated by Django 3.0.7 on 2020-06-11 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20200610_1253'),
        ('responses', '0003_auto_20200610_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='chats.Chat'),
        ),
    ]
