# Generated by Django 3.0.7 on 2020-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200610_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='chats',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='second_user',
        ),
    ]
